//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TapHoa.Models
{
    using System;
    using System.Collections.Generic;
    using TapHoa.Controllers.Memento;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string DCHI { get; set; }
        public string SDT { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public List<string> notifications = new List<string>();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }

        public void Update(SANPHAM sanPham)
        {
            this.notifications.Add($"Nhan vien {HOTEN} nhan thong bao san pham: {sanPham.TENSP} co su thay doi!");
        }
    }
}
